development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3

production:
  adapter: postgresql
  host: db
  port: 5432
  encoding: unicode
  database: dbname
  pool: 5
  username: postgres
  password: supersecret

test:
  adapter: sqlite3
  encoding: unicode
  database: db/production.sqlite3
