source 'https://rubygems.org'

gem 'activerecord'
gem 'attr_extras'
gem 'pg'
gem 'treetop-dcf'

group :test do
  gem 'database_cleaner'
  gem 'webmock'
end

group :development, :test do
  gem 'rubocop'
end
