AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150
