version: '3.3'

services:
  importer:
    build: importer
    depends_on:
      - db
    environment:
      - DATABASE_ENV=development
    env_file:
      - .env
    ports:
      - "8080:4567"

  db:
    restart: always
    image: postgres:9.5-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD:'supersecret'
      - POSTGRES_DB:'dbname'
    volumes:
      - "./docker/db:/docker-entrypoint-initdb.d"
