version: '3.3'

services:
  importer:
    build: importer
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=username
      - POSTGRES_DB=dbname
