development: &dev
  adapter: postgresql
  host: db
  port: 5432
  encoding: unicode
  database: dbname
  pool: 5
  username: postgres
  password: supersecret

production:
  <<: *dev

test:
  <<: *dev
