development:
  adapter: postgresql
  host: pg
  encoding: unicode
  database: postgres_development
  pool: 5
  username: root

production:
  host: pg
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
  username: root

test:
  host: pg
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5
  username: root
