development:
  adapter: postgresql
  host: db
  port: 5432
  encoding: unicode
  database: postgres_development
  pool: 5
  username: username
  password: supersecret

production:
  host: db
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
  username: username
  password: supersecret

test:
  host: db
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5
  username: username
  password: supersecret
